"""Add User Degree

Revision ID: 01acfa57c4db
Revises: b26a9d4aec46
Create Date: 2025-08-29 10:16:13.883235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01acfa57c4db'
down_revision: Union[str, Sequence[str], None] = 'b26a9d4aec46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_degrees_id'), 'degrees', ['id'], unique=False)
    op.create_index(op.f('ix_degrees_name'), 'degrees', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_degrees_name'), table_name='degrees')
    op.drop_index(op.f('ix_degrees_id'), table_name='degrees')
    # ### end Alembic commands ###
