"""Migrations

Revision ID: 3437a9b2f001
Revises: 
Create Date: 2025-08-29 18:23:43.269704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3437a9b2f001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_degrees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_degrees',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('degree_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'degree_id')
    )
    # ### end Alembic commands ###
